version: '3.8'

services:
  postgres:
    container_name: postgresql-personal
    image: postgres:16
    ports:
      - '5532:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker-postgres-db.env

  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets    

volumes:
  db:
  mssql-db: